language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y yasm
  - curl https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-linux.tar.gz | tar xz -C /usr/local/bin

before_script:
  - premake5 gmake
