language: c

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: trusty
      env: TARGET_ARCH=32
    - os: osx
    - os: osx
      env: TARGET_ARCH=32
    - os: linux
      dist: trusty
      env: TARGET_OS=mingw
    - os: linux
      dist: trusty
      env: TARGET_OS=mingw TARGET_ARCH=32

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y yasm; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh -c 'curl -L -s https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-linux.tar.gz | tar xz -C /usr/local/bin'; fi
  - if [[ "$TARGET_OS" == "mingw" ]]; then sudo apt-get install -y mingw-w64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install premake --devel; fi

before_script:
  - if [[ "$TARGET_OS" == "mingw" ]]; then premake5 --os=window gmake; else premake5 gmake; fi

script:
  - if [[ "$TARGET_ARCH" == "32" ]]; then make config=release32; else make config=release64; fi
